import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import session from 'express-session';
import connectPgSimple from 'connect-pg-simple';
import {authRoutes} from './auth/routes.js';
import {createLLM} from './ai/llmClient.js';
import {transcriptRoutes} from './routes/transcript.js';
import {projectRoutes} from './routes/projects.js';
import {teamRoutes} from './routes/team.js';
import {taskRoutes} from './routes/tasks.js';
import {requireAuth,originGuard} from './auth/middleware.js';
import { loadConfig } from './config.js';
import { AppError, notFound, errorHandler } from './lib/errors.js';
import { healthRoutes } from './routes/health.js';
export function createApp({pool,llm,config = loadConfig()}) {
  const app = express();
  app.disable('x-powered-by');
  if (config.production) app.set('trust proxy',1);
  app.use(helmet());
  app.use((req,res,next) => { const start=Date.now(), path=req.path; res.on('finish',()=>console.log(req.method,path,res.statusCode,Date.now()-start+'ms')); next(); });
  app.use(cors({origin(origin,cb) { cb(origin && !config.origins.includes(origin) ? new AppError(403,'FORBIDDEN','This origin is not allowed.') : null, true); },credentials:true}));
  app.use(express.json({limit:'1mb'}));
  app.use('/api',healthRoutes(pool));
  app.use(originGuard(config.origins));
  const Store=connectPgSimple(session);
  const store=new Store({pool,createTableIfMissing:true,pruneSessionInterval:false});
  app.locals.sessionStore=store;
  app.use(session({store,name:'nw.sid',secret:config.sessionSecret,resave:false,saveUninitialized:false,cookie:{...config.cookie,maxAge:config.sessionTTL}}));
  app.use('/api/auth',authRoutes(pool,config));
  app.use('/api/team',requireAuth(pool),teamRoutes(pool));
  app.use('/api/projects',requireAuth(pool),projectRoutes(pool));
  app.use('/api/tasks',requireAuth(pool),taskRoutes(pool));
  app.use('/api/transcript',requireAuth(pool),transcriptRoutes({pool,llm:llm || createLLM(config),config}));
  app.use(notFound);
  app.use(errorHandler);
  return app;
}
